Tickets/dm 29961
lsst-ts/ts_phosim pull request #49
Opened 2021-05-11 02:39 UTC by suberlak

This updates the call to the `phosim_repackager.py` in `PhosimCmpt.py`   adding `focusz`  argument.

2021-05-11 15:00 UTC, teweitsai commented on python/lsst/ts/phosim/PhosimCmpt.py
> +        defocalDistInMm = self.tele.defocalDist
Please consider to use:
```
defocalDistInMm = self.tele.getDefocalDistInMm()
```

BTW, I do not think the `TeleFacade` class has the attribute of `defocalDist`.

2021-05-11 15:03 UTC, teweitsai approved these changes
This update looks good to me. However, the Jenkins test should fail because of the version of `ts_ofc`. Please try to checkout the `v1.3.7` of `ts_ofc` in Jenkinsfile to pass the test:
https://github.com/lsst-ts/ts_phosim/blob/develop/Jenkinsfile#L41-L42

Thanks!

2021-05-12 19:22 UTC, tribeiro requested changes
Instead of merging this, lets merge my PR. I did the exact same "fix" there.

2021-05-12 20:56 UTC, teweitsai commented
I think we need to merge Tiago's ticket branch to `develop` branch first, then, rebase this ticket branch to `develop` branch and fix any failure in this PR.

2021-05-20 03:31 UTC, tribeiro commented
I think we should close this PR. My PR #50 is already implementing it.

2021-05-20 03:31 UTC, closed without merging